#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEMO="$ROOT/demo"

cleanup() {
  echo ""
  echo "Shutting down..."
  # Kill backgrounded anvil if running
  [[ -n "${ANVIL_PID:-}" ]] && kill "$ANVIL_PID" 2>/dev/null || true
  exit 0
}
trap cleanup INT TERM

# ── 1. Start Anvil ──────────────────────────────────────────────
echo "Starting anvil..."
anvil &
ANVIL_PID=$!

# Wait until RPC is up
for i in $(seq 1 30); do
  if cast chain-id --rpc-url http://127.0.0.1:8545 &>/dev/null; then
    break
  fi
  sleep 0.2
done
echo "Anvil running (pid $ANVIL_PID)"

# ── 2. Deploy contracts ─────────────────────────────────────────
echo "Deploying contracts..."
DEPLOY_OUT=$(forge script "$ROOT/script/Deploy.s.sol" \
  --rpc-url http://127.0.0.1:8545 \
  --broadcast 2>&1)

# Parse addresses from forge console.log output
TOKEN_ADDR=$(echo "$DEPLOY_OUT" | grep -i "MockERC20:" | awk '{print $NF}')
SENIOR_ADDR=$(echo "$DEPLOY_OUT" | grep -i "SeniorSecured:" | awk '{print $NF}')
MEZZANINE_ADDR=$(echo "$DEPLOY_OUT" | grep -i "Mezzanine:" | awk '{print $NF}')
STRUCTURED_ADDR=$(echo "$DEPLOY_OUT" | grep -i "Structured:" | awk '{print $NF}')

if [[ -z "$TOKEN_ADDR" || -z "$SENIOR_ADDR" || -z "$MEZZANINE_ADDR" || -z "$STRUCTURED_ADDR" ]]; then
  echo "ERROR: Could not parse deployed addresses from forge output:"
  echo "$DEPLOY_OUT"
  kill "$ANVIL_PID" 2>/dev/null || true
  exit 1
fi

echo "  MockERC20:      $TOKEN_ADDR"
echo "  SeniorSecured:  $SENIOR_ADDR"
echo "  Mezzanine:      $MEZZANINE_ADDR"
echo "  Structured:     $STRUCTURED_ADDR"

# ── 3. Write addresses to demo ──────────────────────────────────
ADDR_FILE="$DEMO/src/addresses.ts"
cat > "$ADDR_FILE" <<EOF
// Auto-generated by demo/start.sh — do not edit manually

export type FacilityKey = "senior" | "mezzanine" | "structured";

export const TOKEN_ADDRESS = "${TOKEN_ADDR}" as \`0x\${string}\`;

export const FACILITIES: Record<FacilityKey, \`0x\${string}\`> = {
  senior: "${SENIOR_ADDR}" as \`0x\${string}\`,
  mezzanine: "${MEZZANINE_ADDR}" as \`0x\${string}\`,
  structured: "${STRUCTURED_ADDR}" as \`0x\${string}\`,
};

export const FACILITY_KEYS: FacilityKey[] = ["senior", "mezzanine", "structured"];
EOF
echo "Wrote $ADDR_FILE"

# ── 4. Start Next.js dev server ─────────────────────────────────
echo ""
echo "Starting Next.js dev server..."
cd "$DEMO"
npm run dev &
NEXT_PID=$!

wait "$NEXT_PID"
