// Auto-generated by demo/start.sh — do not edit manually

export type FacilityKey = "senior1" | "senior2" | "senior3";

export const TOKEN_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3" as `0x${string}`;

export const FACILITIES: Record<FacilityKey, `0x${string}`> = {
  senior1: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9" as `0x${string}`,
  senior2: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707" as `0x${string}`,
  senior3: "0x0165878A594ca255338adfa4d48449f69242Eb8F" as `0x${string}`,
};

export const FACILITY_KEYS = ["senior1", "senior2", "senior3"] as const;
